class CData:
    def __int__(self) -> int: ...
    def __getitem__(self, index: int) -> int: ...

class FFI:
    NULL: CData

    def cdef(self, csource: str, override: bool = ...) -> None: ...
    def dlopen(self, name: str, flags: int = ...) -> object: ...
    def new(self, cdecl: str) -> CData: ...
    def cast(self, cdecl: str, source: object) -> CData: ...
