# Subset of xcffib 1.12 used by the X11 adapter; extend from upstream source.

from collections.abc import Iterator

from . import xproto

CurrentTime: int

class XcffibException(Exception): ...
class ConnectionException(XcffibException): ...
class Error(XcffibException): ...
class ExtensionKey[T]: ...

class Cookie[T]:
    def reply(self) -> T: ...

class List[T]:
    def __iter__(self) -> Iterator[T]: ...
    def to_string(self) -> str: ...
    def buf(self) -> bytes: ...

class Connection:
    pref_screen: int
    core: xproto.xprotoExtension
    def __init__(
        self, display: str | None = ..., fd: int = ..., auth: bytes | None = ...
    ) -> None: ...
    def __call__[T](self, key: ExtensionKey[T]) -> T: ...
    def get_setup(self) -> xproto.Setup: ...
    def disconnect(self) -> None: ...

connect = Connection
